-- MySQL Script generated by MySQL Workbench
-- Thu Mar 14 15:06:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema homeservice
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `homeservice` ;

-- -----------------------------------------------------
-- Schema homeservice
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `homeservice` DEFAULT CHARACTER SET utf8mb3 ;
USE `homeservice` ;

-- -----------------------------------------------------
-- Table `homeservice`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeservice`.`direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `homeservice`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeservice`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `avatar` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `homeservice`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeservice`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `cliente_usuario_id` INT NULL DEFAULT NULL,
  `cliente_direccion_id` INT NULL DEFAULT NULL,
  `clasificacion` TINYINT NULL DEFAULT NULL,
  `activo` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni` (`dni` ASC) VISIBLE,
  INDEX `cliente_usuario_id_idx` (`cliente_usuario_id` ASC) VISIBLE,
  INDEX `cliente_direccion_id_idx` (`cliente_direccion_id` ASC) VISIBLE,
  CONSTRAINT `cliente_direccion_id`
    FOREIGN KEY (`cliente_direccion_id`)
    REFERENCES `homeservice`.`direcciones` (`id`),
  CONSTRAINT `cliente_usuario_id`
    FOREIGN KEY (`cliente_usuario_id`)
    REFERENCES `homeservice`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `homeservice`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeservice`.`compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `clientes_id` INT NULL DEFAULT NULL,
  `total` DECIMAL(18,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compras_clientes1_idx` (`clientes_id` ASC) VISIBLE,
  CONSTRAINT `fk_compras_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `homeservice`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `homeservice`.`profesionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeservice`.`profesionales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `cuit` VARCHAR(45) NOT NULL,
  `profesional_usuario_id` INT NULL DEFAULT NULL,
  `PROFESION` ENUM('OTHERS', 'PLUMBER', 'ELECTRICIAN', 'CONSTRUCTION_WORKER', 'PAINTER', 'GARDENER', 'GASMAN', 'TEACHER', 'PROGRAMMER', 'DESIGNER', 'NANNY') NOT NULL DEFAULT 'OTHERS',
  `profesional_direccion_id` INT NULL DEFAULT NULL,
  `cbu` VARCHAR(45) NOT NULL,
  `clasificacion` INT NULL DEFAULT NULL,
  `activo` TINYINT NOT NULL DEFAULT '1',
  `billetera` DECIMAL(18,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cuit` (`cuit` ASC) VISIBLE,
  INDEX `profesional_usuario_id_idx` (`profesional_usuario_id` ASC) VISIBLE,
  INDEX `profesional_direccion_id_idx` (`profesional_direccion_id` ASC) VISIBLE,
  CONSTRAINT `profesional_direccion_id`
    FOREIGN KEY (`profesional_direccion_id`)
    REFERENCES `homeservice`.`direcciones` (`id`),
  CONSTRAINT `profesional_usuario_id`
    FOREIGN KEY (`profesional_usuario_id`)
    REFERENCES `homeservice`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `homeservice`.`ordenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeservice`.`ordenes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(250) NOT NULL,
  `profesional_id` INT NULL DEFAULT NULL,
  `descripcion_profesional` VARCHAR(1500) NULL DEFAULT NULL,
  `precio` DECIMAL(18,2) NULL DEFAULT NULL,
  `fecha` DATE NOT NULL,
  `ESTADO` ENUM('Inicial', 'Pendiente', 'Aprobada', 'Finalizada') NOT NULL DEFAULT 'Inicial',
  `cliente_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `profesional_id_idx` (`profesional_id` ASC) VISIBLE,
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `ordenes_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `homeservice`.`clientes` (`id`),
  CONSTRAINT `profesional_id`
    FOREIGN KEY (`profesional_id`)
    REFERENCES `homeservice`.`profesionales` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `homeservice`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeservice`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(18,2) NOT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `cantidad` INT NOT NULL DEFAULT '1',
  `foto` TEXT NULL DEFAULT NULL,
  `profesionales_id` INT NULL DEFAULT NULL,
  `activo` TINYINT NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  INDEX `fk_productos_profesionales1_idx` (`profesionales_id` ASC) VISIBLE,
  CONSTRAINT `fk_productos_profesionales1`
    FOREIGN KEY (`profesionales_id`)
    REFERENCES `homeservice`.`profesionales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = '		';


-- -----------------------------------------------------
-- Table `homeservice`.`detalles_productos_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `homeservice`.`detalles_productos_compras` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productos_id` INT NULL DEFAULT NULL,
  `compras_id` INT NULL DEFAULT NULL,
  `cantidad` INT NOT NULL,
  `descuento` DECIMAL(18,2) NULL DEFAULT NULL,
  INDEX `fk_productos_has_compras_compras1_idx` (`compras_id` ASC) VISIBLE,
  INDEX `fk_productos_has_compras_productos1_idx` (`productos_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_productos_has_compras_productos1`
    FOREIGN KEY (`productos_id`)
    REFERENCES `homeservice`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_has_compras_compras1`
    FOREIGN KEY (`compras_id`)
    REFERENCES `homeservice`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
